#### Data Analysis introduction:
#### Data:
        - it is collection of raw data/information
#### data analysis:
        - data analysis is the technique of collecting and transforming and organizing the data to make future predictions and informed data driven decisions.

#### types of data:
        - structured data
                - data that has a standardized format(rows,columns format)
                - ex:table
        - un structured data
                - data that is not defined and easily searchable
                - ex:
                    video files,messages,online reviews,social media post...
        - semi-structured data
                - it contains tags and elements
                - ex:
                        html file,xml files,json files
                        
#### types of data in statistics:
        - numerical data (or) quantitative data
                - which is made of numbers
                - again the data will be divided into 2 types of data
                        - discreate data
                                ex: no of childerns,no of students in a classroom,no of workers in company
                        - continuous data
                                ex:height,age,speed of a car....
                                
        - categorical data (or) qualitative data
                - which is made in characters
                    - nominal data
                            ex:gender,hair color...
                    - ordinal data
                            ex: letters,grades,economic status....

#### python libraries for data analysis:
            - numpy
            - pandas
            - matplot lib
            - seaborn 

#### numpy:
    - numpy stands for numerical python
    - which is used to create multi-dimensional arrays in python
    
#### library installation
    - pip install package name
        - pip install numpy
        
#### library usage:
        - import numpy

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
np.__version__

'1.21.5'

#### how to create array by using numpy
        - numpy.array([e1,e2,e3,e4.....en])

In [8]:
a=np.array([67,89,34,23,56])
a

array([67, 89, 34, 23, 56])

In [9]:
type(a)

numpy.ndarray

#### attributes on numpy arrays:
        - ndim
        - dtype
        - shape
        - nbytes
        - size
        - itemsize
        

In [16]:
print(a)
print(a.ndim) # it returns dimensions of an array
print(a.dtype) # it returns data type of an array
print(a.shape) # it return no of rows and no of columns in given array
print(a.size)  # it returns total elements length in array
print(a.nbytes)# it returns total bytes of an array
print(a.itemsize) # it return each element size in bytes format

[67 89 34 23 56]
1
int32
(5,)
5
20
4


#### how to create an array by using arange function:
        - arange(array range)
        - syntax:
                np.arange(p1,p2,p3)
        - arange(start range,end range+1,step value)

In [17]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(0,51,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [19]:
np.arange(1,51,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [20]:
np.arange(500,601,4)

array([500, 504, 508, 512, 516, 520, 524, 528, 532, 536, 540, 544, 548,
       552, 556, 560, 564, 568, 572, 576, 580, 584, 588, 592, 596, 600])

In [24]:
#### numpy methods:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [28]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [30]:
#### zeros(size)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [38]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
#### ones()
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
#### full(size,element)
np.full(6,4)

array([4, 4, 4, 4, 4, 4])

In [44]:
np.full(5,"numpy")

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy'], dtype='<U5')

In [45]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [46]:
np.full((4,5),'str')

array([['str', 'str', 'str', 'str', 'str'],
       ['str', 'str', 'str', 'str', 'str'],
       ['str', 'str', 'str', 'str', 'str'],
       ['str', 'str', 'str', 'str', 'str']], dtype='<U3')