### Day objectives:
    - numpy

In [1]:
import numpy as np

#### 2-d array in numpy:
    - it is a combination of more than one 1-d array
    - syntax:
        np.array([[e1,e2,e3,e4],[e1,e2,e3,e4]])

In [2]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
type(b)

numpy.ndarray

In [10]:
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)
print(b.size)
print(b.itemsize)
print(b.nbytes)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32
8
4
32


#### how access elements in 2-d array

In [11]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b[0]  # row index

array([1, 2, 3, 4])

In [13]:
b[1]

array([5, 6, 7, 8])

In [15]:
### row index,element index
b[0,3]

4

In [16]:
b[1]

array([5, 6, 7, 8])

In [17]:
b[1,1]

6

In [19]:
b[:,3]

array([4, 8])

In [21]:
b[:,-1]

array([4, 8])

In [ ]:
3 4
7 8

In [22]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
b[:,1:3]

array([[2, 3],
       [6, 7]])

In [28]:
b[:,2:]

array([[3, 4],
       [7, 8]])

In [25]:
b[:,-2:]

array([[3, 4],
       [7, 8]])

#### 3-d array in numpy:
    - it is a combination of more than one 2-d array
    - syntax:
        np.array([[[e1,e2,e3,e3],[e1,e2,e3,e4]],[[e1,e2,e3,e4],[e1,e2,e3,e4]]])


In [29]:
c=np.array([[[1,2,3,4],[4,5,6,7]],[[9,8,7,6],[2,3,4,5]]])
c

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [36]:
print(c)
print(c.ndim)
print(c.shape)
print(c.dtype)
print(c.itemsize)
print(c.size)
print(c.nbytes)

[[[1 2 3 4]
  [4 5 6 7]]

 [[9 8 7 6]
  [2 3 4 5]]]
3
(2, 2, 4)
int32
4
16
64


#### how to access elements from the 3-d array:

In [ ]:
#### array index,row index,element index

In [37]:
c

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [38]:
c[0]

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [40]:
#### array index,row index
c[0,0]

array([1, 2, 3, 4])

In [41]:
c[0,1]

array([4, 5, 6, 7])

In [42]:
c[1]

array([[9, 8, 7, 6],
       [2, 3, 4, 5]])

In [43]:
c[1,0]

array([9, 8, 7, 6])

In [44]:
c[1,1]

array([2, 3, 4, 5])

In [45]:
#### array index,row index,element index
c

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [48]:
c[0,1,3]

7

In [52]:
c[1,0,1]

8

In [55]:
c[:,0,3]

array([4, 6])

In [56]:
c[:,0,-1]

array([4, 6])

In [60]:
c

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 7, 6],
        [2, 3, 4, 5]]])

In [64]:
c[:,:,1:3]

array([[[2, 3],
        [5, 6]],

       [[8, 7],
        [3, 4]]])

In [67]:
c[:,:,-1]

array([[4, 7],
       [6, 5]])

#### reshaping of the array:
    - it giving a new shape to the original array
    - syntax:
        np.reshape(row size,column size)

In [69]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [70]:
a.size

20

In [71]:
a1=a.reshape(4,5)
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [72]:
a2=a.reshape(5,4)
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [73]:
n=np.arange(1,37)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [74]:
n.size

36

In [77]:
n1=n.reshape(6,6)
n1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

#### iteraton of an array:
        - np.nditer(array)

In [78]:
### 1-d array
l=np.arange(1,7)
l

array([1, 2, 3, 4, 5, 6])

In [79]:
l.size

6

In [82]:
for i in l:
    print(i,end=" ")

1 2 3 4 5 6 

In [83]:
#### 2-d array
l1=l.reshape(3,2)
l1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
for i in l1:
    for j in i:
        print(j,end=" ")
    

1 2 3 4 5 6 

In [90]:
### 3-d array:(2,3,1)
l2=l.reshape(3,2,1)
l2

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [93]:
for i in l2:
    for j in i:
        for k in j:
            print(k,end=" ")

1 2 3 4 5 6 

In [94]:
for i in np.nditer(l2):
    print(i,end=" ")

1 2 3 4 5 6 

In [95]:
for i in np.nditer(l1):
    print(i,end=" ")

1 2 3 4 5 6 

#### statistical and math operations on arrays:

In [96]:
s=np.arange(1,10)
s

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
s.size

9

In [98]:
s1=s.reshape(3,3)
s1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
s1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
np.min(s1)

1

In [101]:
np.max(s1)

9

In [102]:
np.argmin(s1) ## min index

0

In [103]:
np.argmax(s1) ## max index

8

In [104]:
np.mean(s1)

5.0

In [105]:
s1.mean()

5.0

In [106]:
np.median(s1)

5.0

In [107]:
np.var(s1)

6.666666666666667

In [108]:
np.std(s1)

2.581988897471611

In [109]:
np.sum(s1)

45

In [110]:
np.sqrt(s1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [112]:
np.exp(s1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [113]:
np.sin(s1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [114]:
np.cos(s1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [115]:
np.tan(s1)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [116]:
np.log(s1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [117]:
np.log2(s1)

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ],
       [2.80735492, 3.        , 3.169925  ]])

In [118]:
np.log10(s1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [119]:
np.remainder(s1,3)

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [121]:
np.mod(s1,4)

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]], dtype=int32)

In [123]:
np.reciprocal(s1,dtype=float)

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [124]:
np.multiply(s1,5)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [125]:
np.power(s1,3)

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

##### array concatenation:
        np.concatenate(array1,array2)


In [131]:
### 1-d
c1=np.arange(1,10)
c2=np.arange(11,20)
print(c1)
print(c2)
res=np.concatenate((c1,c2))
print(res)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [132]:
### 2-d
c3=c1.reshape(3,3)
c4=c2.reshape(3,3)
res1=np.concatenate((c3,c4))
print(res1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [133]:
#### 3-d
c5=c1.reshape(3,1,3)
c6=c2.reshape(3,1,3)
res2=np.concatenate((c5,c6))
print(res2)

[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[11 12 13]]

 [[14 15 16]]

 [[17 18 19]]]


#### stacking:
        - arranging/organizing in appropriate way
            - horizontal stacking
                - np.hstack()
            - vertical stacking
                - np.vstack()

In [134]:
print(c1)

[1 2 3 4 5 6 7 8 9]


In [141]:
np.hstack((c1,c2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [145]:
np.vstack((c1,c2))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

### random()
        - np.random.randint
        - np.random.randn(+ve,-ve)
        - np.random.normal

In [151]:
np.random.randint(1,10)

3

In [161]:
np.random.randint(1,20,8)

array([ 9, 16, 18, 11,  1, 16, 19, 13])

In [164]:
np.random.randint(1,100,size=(6,6))

array([[18, 16, 69, 87, 81, 17],
       [14,  2, 30, 83, 74,  7],
       [80,  6,  5, 49, 91,  9],
       [52, 25, 80,  2, 47, 70],
       [16, 56, 24, 49, 70, 45],
       [17, 59, 70, 11, 54, 21]])

In [167]:
np.random.randn(10)

array([ 1.62361478,  0.37718803, -1.37704565, -0.57429403, -0.24468776,
       -1.31644368,  0.71626477,  0.22515281, -0.2560854 ,  0.5330885 ])

In [176]:
np.random.normal()

-1.2277224797580546

In [182]:
a=input()
b=input()
print(a)
print(b)

89
90
89
90
